spring:
  application:
    name: lie-server-common
  datasource:
    url: jdbc:mysql://39.107.253.236:3306/library?useUnicode=true&amp;characterEncoding=utf8&amp;emptyStringsConvertToZero=true&amp;zeroDateTimeBehavior=convertToNull&amp;useSSL=false
    username: root
    password:
    driver_class_name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    validationQuery: select 'x'
    maxActive: 20
    initialSize: 1
    minIdle: 3
    maxWait: 600
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    filters: stat
    maxOpenPreparedStatements: 20
    logSlowSql: true
  #aop动态代理 ：如果proxy-target-class 属性值被设置为true，那么基于类的代理将起作用（这时需要cglib库）。
  #如果proxy-target-class属值被设置为false或者这个属性被省略，那么标准的JDK 基于接口的代理将起作用
  aop:
    proxy-target-class=false
server:
  port: 2101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
mybatis:
  mapper-locations:  classpath:mapper/*.xml
  type-aliases-package: com.cn.entity
