spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/369107259/lie-center
          search-paths: config-dir/src/main/resources   # 配置仓库路径
          basedir: c:\\config # 配置中心远程clone下来的配置文件所在的位置。目录不存在的话，系统会自动创建dir目录。默认情况下，克隆下来的文件保存在C:\Users\<当前用户>\AppData\Local\Temp目录下
server:
  port: 1101